
calendar-invitation-panel-intro = { $organizer } vous a invité à :
calendar-invitation-panel-status-new = Vous avez reçu une invitation pour cet évènement.
calendar-invitation-panel-status-processed = Cet évènement a déjà été ajouté à votre agenda.
calendar-invitation-panel-status-updateminor = Ce message contient une mise à jour pour cet évènement.
calendar-invitation-panel-status-updatemajor = Ce message contient une mise à jour pour cet évènement. Vous devez reconfirmer votre présence.
calendar-invitation-panel-status-cancelled = Ce message contient une annulation pour cet évènement.
calendar-invitation-panel-status-cancelled-notfound = Ce message contient une annulation pour un évènement introuvable dans votre agenda.
calendar-invitation-panel-intro-cancel = { $organizer } a annulé :
calendar-invitation-panel-title = { $summary }
calendar-invitation-panel-action-button = Enregistrer
calendar-invitation-panel-view-button = Afficher
calendar-invitation-panel-update-button = Mettre à jour
calendar-invitation-panel-delete-button = Supprimer
calendar-invitation-panel-accept-button = Oui
calendar-invitation-panel-decline-button = Non
calendar-invitation-panel-tentative-button = Peut-être
calendar-invitation-panel-reply-status = * Vous n’avez pas encore décidé ou répondu
calendar-invitation-panel-more-button = Plus
calendar-invitation-panel-menu-item-save =
    .label = Enregistrer dans l’agenda
calendar-invitation-panel-menu-item-save-copy =
    .label = Enregistrer une copie
calendar-invitation-panel-menu-item-toggle-changes =
    .label = Afficher les modifications
calendar-invitation-panel-prop-title-when = Quand :
calendar-invitation-panel-prop-title-location = Lieu :
calendar-invitation-datetime-date = { $dayOfWeek }, { $date }
calendar-invitation-datetime-time = { $time } ({ $timezone })
calendar-invitation-interval-all-day = { $startDate }
calendar-invitation-interval-all-day-between-years = { $startDay } { $startMonth } { $startYear } - { $endDay } { $endMonth } { $endYear }
calendar-invitation-interval-all-day-in-month = { $startDay } - { $endDay } { $month } { $year }
calendar-invitation-interval-all-day-between-months = { $startDay } { $startMonth } - { $endDay } { $endMonth } { $year }
calendar-invitation-interval-same-date-time = { $startDate } <b>{ $startTime }</b> { $timezone }
calendar-invitation-interval-same-day = { $startDate } <b>{ $startTime }</b> – <b>{ $endTime }</b> { $timezone }
calendar-invitation-interval-several-days = { $startDate } <b>{ $startTime }</b> – { $endDate } <b>{ $endTime }</b> { $timezone }
calendar-invitation-panel-prop-title-recurrence = Répétition :
calendar-invitation-panel-prop-title-attendees = Participants :
calendar-invitation-panel-prop-title-description = Description :
calendar-invitation-panel-partstat-accepted = { $count } oui
calendar-invitation-panel-partstat-declined = { $count } non
calendar-invitation-panel-partstat-tentative = { $count } peut-être
calendar-invitation-panel-partstat-needs-action = { $count } en attente
calendar-invitation-panel-partstat-total = { $count } participants
calendar-invitation-panel-prop-title-attachments = Pièces jointes :
calendar-invitation-change-indicator-removed = Supprimé
calendar-invitation-change-indicator-added = Nouveau
calendar-invitation-change-indicator-modified = Modifié
