
calendar-deactivated-notification-events = Tous les agendas sont actuellement désactivés. Activez un agenda existant ou ajoutez-en un nouveau pour créer et modifier des évènements.
calendar-deactivated-notification-tasks = Tous les agendas sont actuellement désactivés. Activez un agenda existant ou ajoutez-en un nouveau pour créer et modifier des tâches.
calendar-notifications-label = Afficher les notifications pour les évènements à venir
calendar-add-notification-button =
    .label = Ajouter une notification


calendar-list-header = Agendas
calendar-no-reminders-tooltip =
    .title = L’agenda { $calendarName } a été mis en sourdine.
calendar-enable-button = Activer
calendar-list-item-context-button =
    .title = Options de l’agenda { $calendarName }
calendar-import-new-calendar = Nouvel agenda…
    .title = Créer ou s’abonner à un nouvel agenda
calendar-refresh-calendars =
    .title = Actualiser tous les agendas et synchroniser les changements
calendar-new-event-primary-button = Nouvel évènement
calendar-new-task-primary-button = Nouvelle tâche


calendar-nav-button-prev-tooltip-day =
    .title = Jour précédent
    .accesskey = r
calendar-nav-button-prev-tooltip-week =
    .title = Semaine précédente
    .accesskey = r
calendar-nav-button-prev-tooltip-multiweek =
    .title = Semaine précédente
    .accesskey = p
calendar-nav-button-prev-tooltip-month =
    .title = Mois précédent
    .accesskey = r
calendar-nav-button-prev-tooltip-year =
    .title = Année précédente
    .accesskey = e
calendar-nav-button-next-tooltip-day =
    .title = Jour suivant
    .accesskey = s
calendar-nav-button-next-tooltip-week =
    .title = Semaine suivante
    .accesskey = s
calendar-nav-button-next-tooltip-multiweek =
    .title = Semaine suivante
    .accesskey = s
calendar-nav-button-next-tooltip-month =
    .title = Mois suivant
    .accesskey = s
calendar-nav-button-next-tooltip-year =
    .title = Année suivante
    .accesskey = v
calendar-today-button-tooltip =
    .title = Aller à aujourd’hui
calendar-view-toggle-day = Journée
    .title = Afficher la journée
calendar-view-toggle-week = Semaine
    .title = Afficher la semaine
calendar-view-toggle-multiweek = Multisemaine
    .title = Afficher plusieurs semaines
calendar-view-toggle-month =   Mois  
    .title = Afficher le mois


calendar-control-bar-menu-button =
    .title = Options de mise en page de l’agenda
calendar-find-events-menu-option =
    .label = Panneau de recherche d’évènements
calendar-hide-weekends-option =
    .label = Semaine de travail seulement
calendar-define-workweek-option =
    .label = Définir les jours de la semaine de travail
calendar-show-tasks-calendar-option =
    .label = Afficher les tâches dans l’agenda


calendar-context-menu-previous-day =
    .label = Jour précédent
    .accesskey = o
calendar-context-menu-previous-week =
    .label = Semaine précédente
    .accesskey = e
calendar-context-menu-previous-multiweek =
    .label = Semaine précédente
    .accesskey = e
calendar-context-menu-previous-month =
    .label = Mois précédent
    .accesskey = r
calendar-context-menu-next-day =
    .label = Jour suivant
    .accesskey = J
calendar-context-menu-next-week =
    .label = Semaine suivante
    .accesskey = S
calendar-context-menu-next-multiweek =
    .label = Semaine suivante
    .accesskey = S
calendar-context-menu-next-month =
    .label = Mois suivant
    .accesskey = M
